ManagementSolution/Management/Models/BirthdayOfTheMonthViewModel.cs
using System.ComponentModel.DataAnnotations;

namespace Management.Models
{
    public class BirthdayOfTheMonthViewModel
    {
        [Display(Name = "Nome")]
        public string Name { get; set; }

        [Display(Name = "Data de nascimento")]
        public string Birthdate { get; set; }

        [Display(Name = "Tipo de pessoa")]
        public string TypeOfPerson { get; set; }
    }
}

ManagementSolution/Management/Models/DependentViewModel.cs
namespace Management.Models
{
    public class DependentViewModel
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Birthdate { get; set; }
        public char Gender { get; set; }
        public int EmployeeId { get; set; }
    }
}

ManagementSolution/Management/Models/EmployeeViewModel.cs
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace Management.Models
{
    public class EmployeeViewModel
    {
        public int Id { get; set; }

        [Required(ErrorMessage = "Preencha o campo")]
        [Display(Name = "Nome")]
        public string Name { get; set; }

        [Required(ErrorMessage = "Preencha o campo")]
        [Display(Name = "CPF")]
        public string CPF { get; set; }

        [Required(ErrorMessage = "Preencha o campo")]
        [Display(Name = "Data de nascimento")]
        public string Birthdate { get; set; }

        [Required(ErrorMessage = "Preencha o campo")]
        [Display(Name = "Telefone")]
        public string Phone { get; set; }

        [Required(ErrorMessage = "Selecione o campo")]
        [Display(Name = "Genêro")]
        public string Gender { get; set; }

        [Required(ErrorMessage = "Preencha o campo")]
        [Display(Name = "Endereço")]
        public string Address { get; set; }

        [Required(ErrorMessage = "Preencha o campo")]
        [Display(Name = "Número")]
        public int AddressNumber { get; set; }

        [Required(ErrorMessage = "Selecione o campo")]
        [Display(Name = "Ativo")]
        public bool IsActive { get; set; }

        public List<DependentViewModel> Dependent { get; set; }
    }
}

ManagementSolution/Management/Models/ErrorViewModel.cs
namespace Management.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

ManagementSolution/Management/Controllers/BirthdayOfTheMonthController.cs
using System;
using Management.Parse;
using Management.Services.Employee.Interfaces;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;

namespace Management.Controllers
{
    public class BirthdayOfTheMonthController : Controller
    {
        private IEmployeeService _employeeService;
        private readonly ILogger<BirthdayOfTheMonthController> _logger;
        public BirthdayOfTheMonthController(IEmployeeService employeeService, ILogger<BirthdayOfTheMonthController> logger)
        {
            this._employeeService = employeeService;
            this._logger = logger;
        }

        public IActionResult Index()
        {
            try
            {
                var birthdayList = this._employeeService.GetBirthdayOfTheMonth();
                return View(ParseDTO.ParseBirthdayList(birthdayList));
            }
            catch (Exception ex)
            {
                this._logger.LogError(ex.Message);
                return RedirectToAction("Index", "Home");
            }
        }
    }
}

ManagementSolution/Management/Controllers/EmployeeController.cs
using System;
using Management.Models;
using Management.Parse;
using Management.Services.Employee.Interfaces;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;

namespace Management.Controllers
{
    public class EmployeeController : Controller
    {

        private IEmployeeService _employeeService;
        private readonly ILogger<EmployeeController> _logger;

        public EmployeeController(IEmployeeService employeeService, ILogger<EmployeeController> logger)
        {
            this._employeeService = employeeService;
            this._logger = logger;
        }

        public ActionResult Index()
        {

            var employeesDTO = this._employeeService.List();

            return View(ParseDTO.ParseEmployee(employeesDTO));
        }

        [HttpGet]
        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public JsonResult Post([FromForm] EmployeeViewModel Request)
        {
            try
            {
                this._employeeService.Save(ParseDTO.ParseEmployee(Request));
                return Json(new { Success = true });
            }
            catch (Exception ex)
            {
                this._logger.LogError(ex.Message);
                return Json(new { Success = false });
            }
        }

        public ActionResult Edit(int id)
        {
            try
            {
                var employeeDTO = this._employeeService.FindById(id);

                return View(ParseDTO.ParseEmployee(employeeDTO));
            }
            catch (Exception ex)
            {
                this._logger.LogError(ex.Message);
                return RedirectToAction(nameof(Index));
            }

        }

        [HttpPost]
        public JsonResult Edit([FromForm] EmployeeViewModel Request)
        {
            try
            {
                this._employeeService.Update(ParseDTO.ParseEmployee(Request));
                return Json(new { Success = true });
            }
            catch (Exception ex)
            {
                this._logger.LogError(ex.Message);
                return Json(new { Success = false });
            }
        }

        public ActionResult Delete(int id)
        {
            try
            {
                this._employeeService.Delete(id);

                return RedirectToAction(nameof(Index));
            }
            catch (Exception ex)
            {
                this._logger.LogError(ex.Message);

                return RedirectToAction(nameof(Index));
            }

        }
    }
}

ManagementSolution/Management/Controllers/HomeController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using Management.Models;

namespace Management.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

ManagementSolution/Management/Views/BirthdayOfTheMonth/Index.cshtml
@model IEnumerable<Management.Models.BirthdayOfTheMonthViewModel>

@{
    ViewData["Title"] = "Index";
}

<h1>Aniversariantes do mês @DateTime.Now.Month</h1>

<table class="table">
    <thead>
        <tr>
            <th style="width:30%;">
                @Html.DisplayNameFor(model => model.Name)
            </th>
            <th style="width:30%;">
                @Html.DisplayNameFor(model => model.Birthdate)
            </th>
            <th style="width:30%;">
                @Html.DisplayNameFor(model => model.TypeOfPerson)
            </th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Birthdate)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.TypeOfPerson)
            </td>
        </tr>
}
    </tbody>
</table>

ManagementSolution/Management/Views/Employee/Create.cshtml
@model Management.Models.EmployeeViewModel

@{
    ViewData["Title"] = "Novo funcionário";
}


<h1>Novo funcionário</h1>

<hr />
<div class="row">
    <div class="col-md-4">
        <form action="/Employee/Create" id="send" method="post">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="CPF" class="control-label"></label>
                <input asp-for="CPF" class="form-control" />
                <span asp-validation-for="CPF" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Birthdate" class="control-label"></label>
                <input asp-for="Birthdate" class="form-control" />
                <span asp-validation-for="Birthdate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Phone" class="control-label"></label>
                <input asp-for="Phone" class="form-control" />
                <span asp-validation-for="Phone" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Gender" class="control-label"></label>
                @*<input asp-for="Gender" class="form-control" />
            <span asp-validation-for="Gender" class="text-danger"></span>*@
                <br />
                @Html.RadioButtonFor(model => model.Gender, "M", false)
                @Html.Label("Masculino")
                @Html.RadioButtonFor(model => model.Gender, "F", false)
                @Html.Label("Feminino")
            </div>
            <div class="form-group">
                <label class="control-label">CEP</label>
                <input id="CEP" maxlength="9" class="form-control" />
            </div>
            <div class="form-group">
                <label asp-for="Address" class="control-label"></label>
                <input asp-for="Address" class="form-control" />
                <span asp-validation-for="Address" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="AddressNumber" class="control-label"></label>
                <input type="number" min="1" asp-for="AddressNumber" class="form-control" />
                <span asp-validation-for="AddressNumber" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="IsActive" class="control-label"></label>
                <br />
                @Html.RadioButtonFor(model => model.IsActive, true, false)
                @Html.Label("Sim")
                @Html.RadioButtonFor(model => model.IsActive, false, false)
                @Html.Label("Não")
                <span asp-validation-for="IsActive" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="button" value="Adicionar dependente" id="add_dependent" class="btn btn-success btn-sm" />
            </div>
            <div class="list-group" id="dependent_list">
            </div>
            <div class="form-group">
                <input type="submit" value="Criar" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Voltar para a lista de funcionários</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
    <script src="~/utils/JQuery-Mask.js"></script>
    <script src="~/utils/CEP.js"></script>
    <script src="~/pages/CreateEmployee/CreateEmployee.js"></script>
}

ManagementSolution/Management/Views/Employee/Edit.cshtml
@model Management.Models.EmployeeViewModel

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>EmployeeViewModel</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form action="Employee/Edit/@Model.Id" id="send" method="post">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group" style="display:none;">
                <label asp-for="Id" class="control-label"></label>
                <input asp-for="Id" class="form-control" />
            </div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="CPF" class="control-label"></label>
                <input asp-for="CPF" class="form-control" />
                <span asp-validation-for="CPF" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Birthdate" class="control-label"></label>
                <input asp-for="Birthdate" class="form-control" />
                <span asp-validation-for="Birthdate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Phone" class="control-label"></label>
                <input asp-for="Phone" class="form-control" />
                <span asp-validation-for="Phone" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Gender" class="control-label"></label>
                <br />
                @{ 
                    Model.Gender = Model.Gender == "Masculino" ? "M" : "F";
                }

                @Html.RadioButtonFor(model => model.Gender, "M", new { @checked = true })
                @Html.Label("Masculino")
                @Html.RadioButtonFor(model => model.Gender, "F", new { @checked = true })
                @Html.Label("Feminino")
            </div>
            <div class="form-group">
                <input type="button" value="Trocar Endereço" class="btn btn-primary btn-sm enable-cep" />
            </div>
            <div class="form-group CEP" style="display:none;">
                <label class="control-label">CEP</label>
                <input id="CEP" maxlength="9" class="form-control" />
            </div>
            <div class="form-group">
                @{
                    var completeAddress = Model.Address.Split("-");
                    var address = completeAddress[0];
                    var AddressNumber = Convert.ToInt32(completeAddress[1].Trim());
                }
                <label asp-for="Address" class="control-label"></label>
                <input asp-for="@address" id="Address" class="form-control" />
                <span asp-validation-for="Address" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="AddressNumber" class="control-label"></label>
                <input type="number" min="1" asp-for="@AddressNumber" class="form-control" />
                <span asp-validation-for="AddressNumber" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="IsActive" class="control-label"></label>
                <br />
                @Html.RadioButtonFor(model => model.IsActive, true, false)
                @Html.Label("Sim")
                @Html.RadioButtonFor(model => model.IsActive, false, false)
                @Html.Label("Não")
            </div>
            <div class="form-group">
                <input type="button" value="Adicionar dependente" id="add_dependent" class="btn btn-success btn-sm" />
            </div>
            <div class="list-group" id="dependent_list">
                @{
                    for (int i = 0; i < Model.Dependent.Count; i++)
                    {
                        <div class="dependent" id=@string.Format("dependent_{0}",i+1)>
                            <div class="form-group">
                                <label class="control-label">@string.Format("Nome do dependente {0}", i + 1)</label>
                                <input class="form-control" id=@string.Format("dependent_name{0}", i+1) type="text" value="@Model.Dependent[i].Name" />
                            </div>

                            <div class="form-group">
                                <label class="control-label">@string.Format("Data de nascimento do dependente {0}", i + 1)</label>
                                <input class="form-control Birth_Dependent" id=@string.Format("dependent_birthdate{0}", i+1) type="text" maxlength="10" value="@Model.Dependent[i].Birthdate" />
                            </div>

                            <div class="form-group">
                                <label class="control-label" style="margin-left:6px;">@string.Format("Genêro do dependente {0}", i + 1)</label> <br>
                                <input id=@string.Format("dependent_gender{0}", i+1) name=@string.Format("dependent_gender{0}", i+1) type="radio" value="M" style="margin-left:6px;" checked="checked" />
                                <label style="margin-left:6px;">Masculino</label>
                                <input style="margin-left:6px;" id=@string.Format("dependent_gender{0}", i+1) name=@string.Format("dependent_gender{0}", i+1) type="radio" value="F" checked="checked" />
                                <label style="margin-left:6px;">Feminino</label>
                            </div>

                            <div class="form-group">
                                <input type="button" class="btn btn-danger btn-sm remove_dependent" id=@string.Format("{0}", i+1) value="Remover dependente" />
                            </div>
                        </div>
                    }
                }
            </div>
            <div class="form-group">
                <input type="submit" value="Salvar" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Voltar para a lista de funcionários</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
    <script src="~/utils/JQuery-Mask.js"></script>
    <script src="~/pages/EditEmployee/EditEmployee.js"></script>
    <script src="~/utils/CEP.js"></script>
}

ManagementSolution/Management/Views/Employee/Index.cshtml
@model IEnumerable<Management.Models.EmployeeViewModel>

@{
    ViewData["Title"] = "Lista de funcionários";
}

<h1>Funcionários</h1>

<p>
    <a asp-action="Create">Criar funcionário</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Id)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.CPF)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Birthdate)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Phone)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Gender)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Address)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.IsActive)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Id)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.CPF)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Birthdate)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Phone)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Gender)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Address)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.IsActive)
            </td>
            <td>
                @Html.ActionLink("Editar", "Edit", new { id=item.Id }) |
                @Html.ActionLink("Deletar", "Delete", new {  id=item.Id  })
            </td>
        </tr>
}
    </tbody>
</table>

ManagementSolution/Management/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center" style="width: 50%; margin: auto;">
    <h1 class="display-4">Bem vindo ao gestor de funcionários</h1>
    <p>Veja os aniversariantes do mês clicando <a href="/BirthdayOfTheMonth">aqui</a>!.</p>
</div>

ManagementSolution/Management/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Management</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <style>

        body {
            background-color: #a9a9a91f;
        }
    </style>
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Gestão de funcionários</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Employee" asp-action="Index">Funcionários</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="BirthdayOfTheMonth" asp-action="Index">Aniversariantes do mês</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - Management - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>